// <auto-generated />
namespace WebShopping.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class WebShoppingv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WebShoppingv2));
        
        string IMigrationMetadata.Id
        {
            get { return "202103140953029_WebShopping-v2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
